json.member_since @user_info['memberSince']
json.avatar_url @user_info['avatar150']
json.city @user_info['city']
json.state @user_info['state']
json.height @user_info['height']
json.weight @user_info['weight']
json.bmi @user_info['bmi']
