json.steps @activity_data['steps']
json.distance @activity_data['distance']
json.calories_out @activity_data['caloriesOut']
json.active_calories @activity_data['activityCalories']
json.active_minutes @activity_data['veryActiveMinutes']
